
function field() {
    //створюємо карту
    brick1 = document.createElement("span");
    brick1.className = "brick";
    brick1.id = "brick1";
    brick2 = document.createElement("span");
    brick2.className = "brick";
    brick2.id = "brick2";
    brick3 = document.createElement("span");
    brick3.className = "brick";
    brick3.id = "brick3";
    brick4 = document.createElement("span");
    brick4.className = "brick";
    brick4.id = "brick4";
    brick5 = document.createElement("span");
    brick5.className = "brick";
    brick5.id = "brick5";
    brick6 = document.createElement("span");
    brick6.className = "brick";
    brick6.id = "brick6";
    brick7 = document.createElement("span");
    brick7.className = "brick";
    brick7.id = "brick7";
    brick8 = document.createElement("span");
    brick8.className = "brick";
    brick8.id = "brick8";
    brick9 = document.createElement("span");
    brick9.className = "brick";
    brick9.id = "brick9";
    brick10 = document.createElement("span");
    brick10.className = "brick";
    brick10.id = "brick10";
    brick11 = document.createElement("span");
    brick11.className = "brick";
    brick11.id = "brick11";
    brick12 = document.createElement("span");
    brick12.className = "brick";
    brick12.id = "brick12";
    brick13 = document.createElement("span");
    brick13.className = "brick";
    brick13.id = "brick13";
    brick14 = document.createElement("span");
    brick14.className = "brick";
    brick14.id = "brick14";
    brick15 = document.createElement("span");
    brick15.className = "brick";
    brick15.id = "brick15";
    brick16 = document.createElement("span");
    brick16.className = "brick";
    brick16.id = "brick16";
    brick17 = document.createElement("span");
    brick17.className = "brick";
    brick17.id = "brick17";
    brick18 = document.createElement("span");
    brick18.className = "brick";
    brick18.id = "brick18";
    brick19 = document.createElement("span");
    brick19.className = "brick";
    brick19.id = "brick19";
    brick20 = document.createElement("span");
    brick20.className = "brick";
    brick20.id = "brick20";
    brick21 = document.createElement("span");
    brick21.className = "brick";
    brick21.id = "brick21";

    igrapole.appendChild(brick1);
    igrapole.appendChild(brick2);
    igrapole.appendChild(brick3);
    igrapole.appendChild(brick4);
    igrapole.appendChild(brick5);
    igrapole.appendChild(brick6);
    igrapole.appendChild(brick7);
    igrapole.appendChild(brick8);
    igrapole.appendChild(brick9);
    igrapole.appendChild(brick10);
    igrapole.appendChild(brick11);
    igrapole.appendChild(brick12);
    igrapole.appendChild(brick13);
    igrapole.appendChild(brick14);
    igrapole.appendChild(brick15);
    igrapole.appendChild(brick16);
    igrapole.appendChild(brick17);
    igrapole.appendChild(brick18);
    igrapole.appendChild(brick19);
    igrapole.appendChild(brick20);
    igrapole.appendChild(brick21);
}

field();
